### ISSUE TITLE
Pcbs.io link dead

### ISSUE THREAD

**Issue by BenCos17** [attexx/rfm9x_breakout_board#1]
Just went to the pcbs.io link and it gives a domain for sale page so I assume they don't exist anymore btw

**Comment by attexx** [comment]
you could order your copies of the RFM95x breakout board from the AISLER manufacturing site using the following url:  https://aisler.net/p/BNYBJOFL

**Comment by BenCos17** [comment]
yep 
might be worth editing that part out btw
